[package]
name = "unswayed-server"
version = "0.1.0"
authors = ["Martichou <martichou.andre@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1.1.1"
actix-web = { version = "2.0.0", features = ["openssl"] }
actix-multipart = "0.2.0"
actix-web-httpauth = "0.4.1"
diesel = { version = "1.4.4", features = ["postgres", "r2d2", "chrono"] }
chrono = { version = "0.4.11", features = ["serde"] }
sanitize-filename = "0.2"
derive_more = "0.99.7"
serde_derive = "1.0"
serde_json = "1.0"
futures = "0.3.5"
dotenv = "0.15.0"
nanoid = "0.3.0"
r2d2 = "0.8.8"
serde = "1.0"
openssl = "0.10.29"
async-std = "1.6.0"
rusoto_s3 = "0.44.0"
rusoto_core = "0.44.0"