[package]
name = "unswayed-server"
version = "0.1.0"
authors = ["Martichou <martichou.andre@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1.1.1"
actix-web = "2.0.0"
diesel = { version = "1.4.4", features = ["postgres", "r2d2", "chrono"] }
chrono = { version = "0.4.11", features = ["serde"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
futures = "0.3.5"
dotenv = "0.15.0"
r2d2 = "0.8.8"
nanoid = "0.3.0"